Authorization: YOUR_TWITCH_AUTHORIZATION
Client-Id: YOUR_CLIENT_ID
Client-Integrity: YOUR_CLIENT_INTEGRITY
X-Device-Id: YOUR_DEVICE_ID
Content-Type: text/plain;charset=UTF-8


# Whitelist channels to not be unfollowed (optional - case sensitive - usernames only)
## Currently not working - gets stuck in a loop... if you find a fix, please let me know! :)
#Whitelist:
#  - username1